const rolesExtraData = {
  "MBL": {
    descFull: "Participiante del MBL es un ejeutivo inmerso directa o indirectamente en la cadena de suministro. Idealmente cuenta con experiencia multicultural y en otras compañías/industrias. Seleccionado por los resultados demostrados, su potencial de liderazgo, una ambición genuina por asumir nuevos retos y responsabilidades y por su alineación con la filosofía y cultura de la compañía.",
    allCaps: [{cap:"Finanzas",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.6,nivel:"Proficient"},{cap:"Grit (resilencia + empuje)",puntaje:2.5,nivel:"Proficient"},{cap:"Planificación de la estrategia",puntaje:2.2,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2.3,nivel:"Proficient"},{cap:"Deliver and Transform",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de la cadena de suministro",puntaje:2.3,nivel:"Proficient"},{cap:"Negociación",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2.5,nivel:"Proficient"}]
  },
  "Supervisor de Almacén": {
    descFull: "Planificar, coordinar, estandarizar y medir las operaciones de los almacenes de los CDD (Centros de Distribución), a través del cumplimiento de las políticas y procedimientos establecidos en DPO, a fin de entregar  productos con seguridad, calidad y al menor costo posible para la distribución.",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:1.8,nivel:"Competent"},{cap:"Management by Walking Around (MBWA)",puntaje:2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:1.9,nivel:"Competent"},{cap:"Orientación a datos",puntaje:1.8,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.9,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Finanzas",puntaje:2,nivel:"Competent"},{cap:"Almacenamiento Digital",puntaje:1.7,nivel:"Competent"},{cap:"Inglés",puntaje:1.7,nivel:"Competent"}]
  },
  "Supervisor de Distribución": {
    descFull: "Garantizar el buen servicio y entrega de los productos de la empresa a la totalidad de los clientes, al más bajo costo; con la mayor productividad posible. ",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:1.9,nivel:"Competent"},{cap:"Customer Centricity",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2,nivel:"Competent"},{cap:"Management by Walking Around (MBWA)",puntaje:2,nivel:"Competent"},{cap:"Negociación",puntaje:1.9,nivel:"Competent"},{cap:"Entrega Digital",puntaje:1.8,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2.1,nivel:"Competent"},{cap:"Orientación a datos",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:1.8,nivel:"Competent"}]
  },
  "Gerente Flota T2": {
    descFull: "Gestionar de forma efectiva el mantenimiento preventivo, predictivo y correctivo de la flota. Participar de forma activa en la elaboración de presupuestos de garantizar la ejecución del mismo conforme a las normas y estándares de calidad exigidos por los fabricantes y programas de excelencia internos (VPO, DPO).       ",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2,nivel:"Competent"},{cap:"Gestión de interesados",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de flota",puntaje:2.5,nivel:"Proficient"},{cap:"Management by Walking Around (MBWA)",puntaje:2.3,nivel:"Proficient"},{cap:"Organización avanzada",puntaje:2.2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.5,nivel:"Proficient"},{cap:"Planificación de capacidad",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de contratos",puntaje:2.3,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.5,nivel:"Proficient"},{cap:"Deliver and Transform",puntaje:2.1,nivel:"Competent"},{cap:"Inglés",puntaje:2.1,nivel:"Competent"}]
  },
  "Gerente de Ruteo": {
    descFull: "Liderar y dirigir la implementación estándar de estrategias de planificación de territorios, rutas y monitoreo de flotas de acuerdo a las políticas definidas para cada región, asegurando mediante el uso correcto de las herramientas de ruteo, la optimización de los recursos, el servicio al cliente, la seguridad vial y la contribución al reducción de costos logísticos en T2, asegurando un alto nivel de calidad en el servicio y un ambiente operativo seguro",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2.6,nivel:"Proficient"},{cap:"Gestión de equipos",puntaje:2.4,nivel:"Proficient"},{cap:"Gestión de interesados",puntaje:2.5,nivel:"Proficient"},{cap:"Ruteo",puntaje:2.7,nivel:"Expert"},{cap:"Gestión por sistemas",puntaje:2.4,nivel:"Proficient"},{cap:"Management by Walking Around (MBWA)",puntaje:2.4,nivel:"Proficient"},{cap:"Planificación de capacidad",puntaje:2.4,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.4,nivel:"Proficient"},{cap:"Deliver and Transform",puntaje:2.1,nivel:"Competent"},{cap:"Técnicas de Optimización",puntaje:2.4,nivel:"Proficient"},{cap:"ITIL + COBIT",puntaje:2.2,nivel:"Competent"},{cap:"Inglés",puntaje:2.1,nivel:"Competent"}]
  },
  "Especialista de Ruteo": {
    descFull: "Planificar las rutas diarias de entrega de los vehículos de distribución de la Región asignada, mediante el uso correcto de la herramienta de ruteo, garantizando el cumplimiento de las visitas a nuestros clientes y optimizando el uso de la flota, identificando así mismo oportunidades de mejora en el proceso de planificación y ejecución. de las rutas, con el fin de mejorar los indicadores operativos de la VP de logística.",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2.1,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2.1,nivel:"Competent"},{cap:"Ruteo",puntaje:2.2,nivel:"Competent"},{cap:"Customer Centricity",puntaje:2.2,nivel:"Competent"},{cap:"Comunicación",puntaje:2.1,nivel:"Competent"},{cap:"Trabajo bajo presión",puntaje:2.2,nivel:"Competent"},{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Distribucion T2 / Ultima Milla",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.1,nivel:"Competent"},{cap:"Técnicas de Optimización",puntaje:2.5,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.1,nivel:"Competent"},{cap:"Inglés",puntaje:1.8,nivel:"Competent"}]
  },
  "Gerente de Monitoreo": {
    descFull: "Garantizar la disponibilidad, confiabilidad y rendimiento óptimo de los sistemas y servicios críticos a través de una supervisión efectiva, coordinación de actividades, gestión de incidentes y optimización de procesos en el área.",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2.6,nivel:"Proficient"},{cap:"Gestión de equipos",puntaje:2.4,nivel:"Proficient"},{cap:"Operaciónes de Distribución de T2",puntaje:2.3,nivel:"Proficient"},{cap:"Data Driven / Analítico",puntaje:2.4,nivel:"Proficient"},{cap:"Gestión de interesados",puntaje:2.3,nivel:"Proficient"},{cap:"Customer Centricity",puntaje:2.3,nivel:"Proficient"},{cap:"Pensamiento Sistémico",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de crisis",puntaje:2.3,nivel:"Proficient"},{cap:"Deliver and Transform",puntaje:2.2,nivel:"Competent"},{cap:"Finanzas",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2,nivel:"Competent"}]
  },
  "Coordinador de Monitoreo": {
    descFull: "Coordinar las actividades, entrenamientos del equipo de monitoristas safety, productividad, desarrollo; con el objetivo de garantizar los resultados esperados en cada pilar y para satisfacer las necesidades de los diferentes clientes con los que el equipo interactúa. ",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2.2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2.1,nivel:"Competent"},{cap:"Operaciónes de Distribución de T2",puntaje:2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2.1,nivel:"Competent"},{cap:"Comunicación",puntaje:2.1,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.9,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de crisis",puntaje:2.1,nivel:"Competent"},{cap:"Deliver and Transform",puntaje:2.1,nivel:"Competent"},{cap:"Finanzas",puntaje:2,nivel:"Competent"}]
  },
  "Especialista de Monitoreo": {
    descFull: "Gestionar alertas de safety y productividad de las unidades de T2 en tiempo real, asegurando la seguridad de los tripulantes; a partir de dar visibilidad de lo que sucede en la calle en cada una de las operaciones.",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.9,nivel:"Competent"},{cap:"Ruteo y monitoreo (digital control tower)",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:1.8,nivel:"Competent"},{cap:"Operaciónes de Distribución de T2",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de flota",puntaje:1.8,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:1.7,nivel:"Competent"},{cap:"Seguridad",puntaje:2.2,nivel:"Competent"},{cap:"Productividad",puntaje:1.9,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:1.8,nivel:"Competent"}]
  },
  "Coordinador de Control T2": {
    descFull: "Controlar las operaciones para la prevención de Pérdidas y dar seguimiento a que se cumplan todos los procesos en el almacén de acuerdo con los establecidos en los padrones de la compañía, para garantizar informaciones y resultado exacto de acuerdo a lo que la empresa espera.",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2.1,nivel:"Competent"},{cap:"Pensamiento crítico",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Autonomía",puntaje:2.1,nivel:"Competent"},{cap:"Impacto e influencia",puntaje:1.9,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.1,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:2.1,nivel:"Competent"},{cap:"Ética laboral",puntaje:2.2,nivel:"Competent"}]
  },
  "Especialista DRP": {
    descFull: "Mantener el plan de inventario frente a las realidades operativas para generar planes de reubicación que maximicen las ganancias.",
    allCaps: [{cap:"DRP con O9",puntaje:2,nivel:"Competent"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Excel",puntaje:2.5,nivel:"Proficient"},{cap:"Estándar LCP para despliegue de inventario",puntaje:2,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:2,nivel:"Competent"},{cap:"Resiliencia",puntaje:2.5,nivel:"Proficient"},{cap:"Empuje / Orientación a resultados",puntaje:2,nivel:"Competent"},{cap:"Transportación y logística",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:2.5,nivel:"Proficient"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"}]
  },
  "Gerente - Logística inversa": {
    descFull: "Optimiza los niveles de inventario de empaques para satisfacer la demanda de productos terminados mientras minimizas los costos logísticos, pérdidas e inversión.",
    allCaps: [{cap:"Orientación a datos",puntaje:2.5,nivel:"Proficient"},{cap:"Colaboración",puntaje:2.6,nivel:"Proficient"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Excel",puntaje:1.8,nivel:"Competent"},{cap:"Estándares de logística inversa LCP y mantenimiento del inventario",puntaje:2.5,nivel:"Proficient"},{cap:"Planificación y Organización",puntaje:2.5,nivel:"Proficient"},{cap:"Resiliencia",puntaje:2.8,nivel:"Expert"},{cap:"Toma de Decisiones",puntaje:2.3,nivel:"Proficient"},{cap:"Negociación",puntaje:2.3,nivel:"Proficient"},{cap:"Mejora continua",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión por sistemas",puntaje:2.3,nivel:"Proficient"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"}]
  },
  "Especialista - CONA": {
    descFull: "Calcula rutas de transferencia óptimas para suministrar producto terminado y mínimos costos teniendo en cuenta los requisitos de distribución y las limitaciones de capacidad al menor costo.",
    allCaps: [{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:3,nivel:"Expert"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Gestión de interesados",puntaje:2,nivel:"Competent"},{cap:"Estándares de S&OP LCP + SNP LCP",puntaje:2,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2,nivel:"Competent"},{cap:"Finanzas empresariales",puntaje:2,nivel:"Competent"},{cap:"Planificación de capacidad",puntaje:1,nivel:"Novice"},{cap:"Técnicas de Optimización",puntaje:3,nivel:"Expert"},{cap:"Resolución de problemas y causa raíz",puntaje:2,nivel:"Competent"},{cap:"CONA con O9",puntaje:2,nivel:"Competent"}]
  },
  "Especialista - NPI": {
    descFull: "Gestionar y coordinar el proceso de desarrollo y lanzamiento de nuevos productos al mercado de manera eficiente y efectiva,  optimizazando la integración de nuevos productos en la cadena de suministro, asegurando una transición fluida desde el desarrollo hasta la plena producción y distribución.",
    allCaps: [{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándar LCP para Planeación de la Demanda",puntaje:3,nivel:"Expert"},{cap:"Pronóstico colaborativo",puntaje:3,nivel:"Expert"},{cap:"Sensibilidad del mercado",puntaje:2,nivel:"Competent"},{cap:"Empuje / Orientación a resultados",puntaje:3,nivel:"Expert"},{cap:"Gestión de interesados",puntaje:3,nivel:"Expert"},{cap:"Finanzas empresariales",puntaje:2,nivel:"Competent"},{cap:"Mejora continua",puntaje:2,nivel:"Competent"},{cap:"NPI con O9",puntaje:0.5,nivel:"Novice"}]
  },
  "Especialista - MRP Táctico": {
    descFull: "\"Optimiza los niveles de inventario de materiales para cumplir con la  demanda de productos terminados,  Se centra en la estrategia y en la alineación de los recursos de la empresa con los objetivos de producción y demanda a mediano plazo.\"",
    allCaps: [{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Excel",puntaje:3,nivel:"Expert"},{cap:"Estándares de MRP LCP",puntaje:2,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:3,nivel:"Expert"},{cap:"Resiliencia",puntaje:2,nivel:"Competent"},{cap:"Empuje / Orientación a resultados",puntaje:3,nivel:"Expert"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Planificación de capacidad",puntaje:1,nivel:"Novice"},{cap:"Planeación y gestión de la producción",puntaje:1,nivel:"Novice"},{cap:"Transportación y logística",puntaje:2,nivel:"Competent"}]
  },
  "Especialista - WSNP": {
    descFull: "Crea planes óptimos de producción y distribución para satisfacer la demanda, teniendo en cuenta los niveles de inventario objetivo, las asignaciones de DPG y las decisiones de S&OP.",
    allCaps: [{cap:"Colaboración",puntaje:2.5,nivel:"Proficient"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Excel",puntaje:2.5,nivel:"Proficient"},{cap:"Estándares de planificación de SNP y S&OE y la red de suministro LCP",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:3,nivel:"Expert"},{cap:"Resiliencia",puntaje:3,nivel:"Expert"},{cap:"Empuje / Orientación a resultados",puntaje:2.5,nivel:"Proficient"},{cap:"Planeación y gestión de la producción",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Gestión de riesgos",puntaje:2,nivel:"Competent"},{cap:"Técnicas de Optimización",puntaje:2,nivel:"Competent"},{cap:"WSNP con O9",puntaje:2,nivel:"Competent"}]
  },
  "Especialista - Retpack": {
    descFull: "Analizar los niveles de inventario de envase/empaque para generar planes de compra, fabricación y distribución para mantener inventarios sanos para habilitar el plan de demanda, minimizando la inversión",
    allCaps: [{cap:"Colaboración",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Excel",puntaje:2.5,nivel:"Proficient"},{cap:"Estándares de logística inversa LCP y mantenimiento del inventario y la red de suministro LCP",puntaje:2,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Finanzas empresariales",puntaje:2,nivel:"Competent"},{cap:"Planeación y gestión de la producción",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Transportación y logística",puntaje:1.5,nivel:"Advanced Beginner"}]
  },
  "Especialista - DP Operativo": {
    descFull: "La planeación de la demanda operativa se centra en la gestión a corto plazo de la demanda, asegurando que los productos estén disponibles para satisfacer las necesidades inmediatas del mercado a partir de consideras la realidad del negocio y las tendencias locales. ",
    allCaps: [{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:3,nivel:"Expert"},{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:1,nivel:"Novice"},{cap:"Estándar LCP para Planeación de la Demanda",puntaje:2,nivel:"Competent"},{cap:"Pronóstico colaborativo",puntaje:2,nivel:"Competent"},{cap:"Sensibilidad del mercado",puntaje:2,nivel:"Competent"},{cap:"Empuje / Orientación a resultados",puntaje:2,nivel:"Competent"},{cap:"Métodos estadísticos y de pronóstico",puntaje:2,nivel:"Competent"},{cap:"Gestión de interesados",puntaje:2,nivel:"Competent"},{cap:"Estructuras complejas de datos",puntaje:2.5,nivel:"Proficient"},{cap:"Planeación de la demanda con O9",puntaje:2,nivel:"Competent"}]
  },
  "Gerente - CONA": {
    descFull: "Calcula rutas de transferencia óptimas para suministrar producto terminado y mínimos costos teniendo en cuenta los requisitos de distribución y las limitaciones de capacidad al menor costo.",
    allCaps: [{cap:"Finanzas empresariales",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Gestión de interesados",puntaje:2,nivel:"Competent"},{cap:"Estándares de S&OP LCP + SNP LCP",puntaje:2,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2,nivel:"Competent"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:2,nivel:"Competent"},{cap:"Mejora continua",puntaje:2,nivel:"Competent"}]
  },
  "Especialista DP Estadistico": {
    descFull: "Crear pronósticos de demanda confiables como la referencia para el acuerdo sobre planes de negocios conjuntos para equilibrar el nivel de servicio deseado al costo óptimo",
    allCaps: [{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:3,nivel:"Expert"},{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:1,nivel:"Novice"},{cap:"Estándar LCP para Planeación de la Demanda",puntaje:2,nivel:"Competent"},{cap:"Pronóstico colaborativo",puntaje:1,nivel:"Novice"},{cap:"Sensibilidad del mercado",puntaje:1,nivel:"Novice"},{cap:"Empuje / Orientación a resultados",puntaje:3,nivel:"Expert"},{cap:"Métodos estadísticos y de pronóstico",puntaje:3,nivel:"Expert"},{cap:"Gestión de interesados",puntaje:2,nivel:"Competent"},{cap:"Estructuras complejas de datos",puntaje:3,nivel:"Expert"},{cap:"Planeación de la demanda con O9",puntaje:2,nivel:"Competent"}]
  },
  "Gerente DP Operativo": {
    descFull: "La planeación de la demanda operativa se centra en la gestión a corto plazo de la demanda, asegurando que los productos estén disponibles para satisfacer las necesidades inmediatas del mercado a partir de consideras la realidad del negocio y las tendencias locales. ",
    allCaps: [{cap:"Excel",puntaje:2.5,nivel:"Proficient"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:3,nivel:"Expert"},{cap:"Colaboración",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Estándar LCP para Planeación de la Demanda",puntaje:3,nivel:"Expert"},{cap:"Pronóstico colaborativo",puntaje:3,nivel:"Expert"},{cap:"Sensibilidad del mercado",puntaje:3,nivel:"Expert"},{cap:"Gestión de interesados",puntaje:3,nivel:"Expert"},{cap:"Gestión por sistemas",puntaje:2.6,nivel:"Proficient"},{cap:"Finanzas empresariales",puntaje:2.6,nivel:"Proficient"},{cap:"Mejora continua",puntaje:2.5,nivel:"Proficient"}]
  },
  "Gerente - DRP": {
    descFull: "Mantener el plan de inventario frente a las realidades operativas para generar planes de reubicación que maximicen las ganancias.",
    allCaps: [{cap:"Inglés",puntaje:3,nivel:"Expert"},{cap:"Orientación a datos",puntaje:2.5,nivel:"Proficient"},{cap:"Colaboración",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de inventarios",puntaje:3,nivel:"Expert"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándar LCP para despliegue de inventario",puntaje:3,nivel:"Expert"},{cap:"Planificación y Organización",puntaje:2.5,nivel:"Proficient"},{cap:"Resiliencia",puntaje:2.2,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2.5,nivel:"Proficient"},{cap:"Negociación",puntaje:2.5,nivel:"Proficient"},{cap:"Mejora continua",puntaje:2.5,nivel:"Proficient"}]
  },
  "Gerente - WSNP": {
    descFull: "El Gerente WSNP (Wholesale & Retail Network Planning) juega un papel crucial en la gestión de la cadena de suministro, liderando la creación de planes óptimos de producción y distribución para satisfacer la demanda, teniendo en cuenta los niveles de inventario objetivo, las asignaciones de DPG (Demand Planning Group) y las decisiones de S&OP (Sales & Operations Planning). A medida que avanzan en su carrera, estos profesionales desarrollan las habilidades y la experiencia necesarias para navegar por la complejidad de la gestión de la cadena de suministro y contribuir al éxito de la empresa.",
    allCaps: [{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándares de planificación de SNP y S&OE y la red de suministro LCP",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:2,nivel:"Competent"},{cap:"Resiliencia",puntaje:2,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2,nivel:"Competent"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Gestión de interesados",puntaje:2,nivel:"Competent"},{cap:"Mejora continua",puntaje:2,nivel:"Competent"}]
  },
  "Gerente - Retpack": {
    descFull: "Analizar los niveles de inventario de envase/empaque para generar planes de compra, fabricación y distribución para mantener inventarios sanos para habilitar el plan de demanda, minimizando la inversión",
    allCaps: [{cap:"Inglés",puntaje:3,nivel:"Expert"},{cap:"Orientación a datos",puntaje:2.5,nivel:"Proficient"},{cap:"Colaboración",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Excel",puntaje:2.2,nivel:"Competent"},{cap:"Estándares de logística inversa LCP y mantenimiento del inventario y la red de suministro LCP",puntaje:2,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2.5,nivel:"Proficient"},{cap:"Resolución de problemas y causa raíz",puntaje:3,nivel:"Expert"},{cap:"Negociación",puntaje:2.6,nivel:"Proficient"},{cap:"Mejora continua",puntaje:2.6,nivel:"Proficient"},{cap:"Planificación de aprovisionamiento",puntaje:3,nivel:"Expert"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"}]
  },
  "Gerente - MRP Táctico": {
    descFull: "Optimiza los niveles de inventario de materiales para cumplir con la  demanda de productos terminados,  Se centra en la estrategia y en la alineación de los recursos de la empresa con los objetivos de producción y demanda a mediano plazo.",
    allCaps: [{cap:"Inglés",puntaje:3,nivel:"Expert"},{cap:"Orientación a datos",puntaje:2.5,nivel:"Proficient"},{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Gestión de inventarios",puntaje:3,nivel:"Expert"},{cap:"Excel",puntaje:2.5,nivel:"Proficient"},{cap:"Estándares de MRP LCP",puntaje:3,nivel:"Expert"},{cap:"Planificación y Organización",puntaje:3,nivel:"Expert"},{cap:"Resiliencia",puntaje:3,nivel:"Expert"},{cap:"Toma de Decisiones",puntaje:2.5,nivel:"Proficient"},{cap:"Negociación",puntaje:3,nivel:"Expert"},{cap:"Planificación de aprovisionamiento",puntaje:3,nivel:"Expert"},{cap:"Mejora continua",puntaje:2.5,nivel:"Proficient"}]
  },
  "Especialista - MRP Operativo": {
    descFull: "Optimiza los niveles de inventario de materiales para cumplir con la  demanda de productos terminados minimizando costos, centrándose en la ejecución detallada del plan de producción táctico, gestionando las operaciones diarias.",
    allCaps: [{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Gestión de inventarios",puntaje:3,nivel:"Expert"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándares de MRP LCP",puntaje:2,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:2.5,nivel:"Proficient"},{cap:"Resiliencia",puntaje:2.2,nivel:"Competent"},{cap:"Empuje / Orientación a resultados",puntaje:3,nivel:"Expert"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Transportación y logística",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:2,nivel:"Competent"},{cap:"MRP con O9",puntaje:2,nivel:"Competent"}]
  },
  "Gerente - MRP Operativo": {
    descFull: "Optimiza los niveles de inventario de materiales para cumplir con la  demanda de productos terminados minimizando costos, centrándose en la ejecución detallada del plan de producción táctico, gestionando las operaciones diarias.",
    allCaps: [{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Gestión de inventarios",puntaje:3,nivel:"Expert"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándares de MRP LCP",puntaje:2,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:2.5,nivel:"Proficient"},{cap:"Resiliencia",puntaje:2.2,nivel:"Competent"},{cap:"Empuje / Orientación a resultados",puntaje:3,nivel:"Expert"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Transportación y logística",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:2,nivel:"Competent"},{cap:"MRP con O9",puntaje:2,nivel:"Competent"}]
  },
  "Especialista - Programación de la producción": {
    descFull: "Desarrolla métodos, técnicas y herramientas para la planificación eficiente de planes y programaciones que sincronizan eficazmente la demanda con la capacidad de producción, considerando tanto los recursos materiales como humanos.",
    allCaps: [{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándares VPO programación y nivel de servicio",puntaje:2.5,nivel:"Proficient"},{cap:"Técnicas de programación",puntaje:3,nivel:"Expert"},{cap:"Principios de Manufactura",puntaje:2,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Manufactura Esbelta",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Resiliencia",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de interesados",puntaje:2.5,nivel:"Proficient"},{cap:"Programación con Optplan",puntaje:2.5,nivel:"Proficient"}]
  },
  "Gerente Regional de Operaciones - GRO": {
    descFull: "\"Coordinar las actividades de Almacén y Rutas de Entrega del territorio en referencia optimizando los recursos apalancados en productividad  y enfocados en garantizar el mejor nivel de servicio, desarrollando relaciones a largo plazo con nuestros clientes. \"",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2.5,nivel:"Proficient"},{cap:"Mentalidad de crecimiento",puntaje:2.4,nivel:"Proficient"},{cap:"Gestión por sistemas",puntaje:2.6,nivel:"Proficient"},{cap:"Gestion de Interesados",puntaje:2.7,nivel:"Expert"},{cap:"Gestión de equipos",puntaje:2.8,nivel:"Expert"},{cap:"Gestión de la cadena de suministro",puntaje:2.7,nivel:"Expert"},{cap:"Finanzas",puntaje:2.8,nivel:"Expert"},{cap:"Planificación de la estrategia",puntaje:2.6,nivel:"Proficient"},{cap:"Deliver and Transform",puntaje:2.2,nivel:"Competent"},{cap:"Planificación de capacidad",puntaje:2.7,nivel:"Expert"}]
  },
  "Gerente Operaciones de Distribución (GOD)": {
    descFull: "Coordinar las actividades de almacén y rutas de entrega optimizando los recursos apalancados en productividad  y enfocados en garantizar el mejor nivel de servicio, desarrollando relaciones a largo plazo con nuestros clientes.",
    allCaps: [{cap:"Grit (resilencia + empuje)",puntaje:2.2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.4,nivel:"Proficient"},{cap:"Gestion de Interesados",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2.4,nivel:"Proficient"},{cap:"Management by Walking Around (MBWA)",puntaje:2.5,nivel:"Proficient"},{cap:"Inteligencia emocional",puntaje:2.3,nivel:"Proficient"},{cap:"Operaciónes de Distribución de T2",puntaje:2.3,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.5,nivel:"Proficient"},{cap:"Planificación de capacidad",puntaje:2.5,nivel:"Proficient"},{cap:"Deliver and Transform",puntaje:2,nivel:"Competent"}]
  },
  "Gerente - DP Estadístico": {
    descFull: "Crear pronósticos de demanda confiables como la referencia para el acuerdo sobre planes de negocio conjuntos para equilibrar el nivel de servicio deseado al costo óptimo.",
    allCaps: [{cap:"Excel",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Orientación a datos",puntaje:3,nivel:"Expert"},{cap:"Colaboración",puntaje:2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Estándar LCP para Planeación de la Demanda",puntaje:2,nivel:"Competent"},{cap:"Pronóstico colaborativo",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Sensibilidad del mercado",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Gestión de interesados",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión por sistemas",puntaje:2.5,nivel:"Proficient"},{cap:"Finanzas empresariales",puntaje:2,nivel:"Competent"},{cap:"Mejora continua",puntaje:2,nivel:"Competent"}]
  },
  "Especialista - Logística inversa": {
    descFull: "Optimiza los niveles de inventario de empaques para satisfacer la demanda de productos terminados mientras minimizas los costos logísticos, pérdidas e inversión.",
    allCaps: [{cap:"Orientación a datos",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:3,nivel:"Expert"},{cap:"Gestión de inventarios",puntaje:2.5,nivel:"Proficient"},{cap:"Excel",puntaje:2,nivel:"Competent"},{cap:"Estándares de logística inversa LCP y mantenimiento del inventario",puntaje:2,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:2,nivel:"Competent"},{cap:"Resiliencia",puntaje:2.5,nivel:"Proficient"},{cap:"Empuje / Orientación a resultados",puntaje:2,nivel:"Competent"},{cap:"Transportación y logística",puntaje:2,nivel:"Competent"},{cap:"Resolución de problemas y causa raíz",puntaje:2.5,nivel:"Proficient"},{cap:"Negociación",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"}]
  },
  "Gerente PPM": {
    descFull: "Proporciona visibilidad y precisión del costo de SC mediante análisis de datos durante las rutinas en los niveles más altos de la organización. Es responsable de analizar las finanzas y otros KPI del negocio para apoyar a la gerencia de SC en la toma de decisiones estructuradas, basadas en hechos y proactivas, con el fin de aumentar el nivel de servicio con un menor costo para nuestros clientes y procesos presupuestarios adecuados.",
    allCaps: [{cap:"Storytelling",puntaje:2.8,nivel:"Expert"},{cap:"Gestión de riesgo",puntaje:2.5,nivel:"Proficient"},{cap:"Análisis de Costos",puntaje:2.5,nivel:"Proficient"},{cap:"Desarrollo de casos de negocio",puntaje:2.5,nivel:"Proficient"},{cap:"Planificación y análisis financiero",puntaje:2.8,nivel:"Expert"},{cap:"Gestión del conocimiento",puntaje:2.5,nivel:"Proficient"},{cap:"Estrategia de Negocio",puntaje:2.8,nivel:"Expert"},{cap:"Gestión del cambio",puntaje:2.8,nivel:"Expert"},{cap:"Informes Financieros",puntaje:2.5,nivel:"Proficient"},{cap:"Visión del Negocio",puntaje:2.5,nivel:"Proficient"},{cap:"Inglés",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de equipos",puntaje:2.5,nivel:"Proficient"}]
  },
  "Ana-Esp PPM": {
    descFull: "Lidera el apoyo clave para aumentar la visibilidad y la precisión de los proyectos mediante el aporte de información analítica. Es responsable del análisis financiero y otros indicadores clave de rendimiento (KPI) del negocio para apoyar a la gerencia de SC en la toma de decisiones estructuradas, basadas en hechos y proactivas, con el fin de mejorar el nivel de servicio con un menor costo para nuestros clientes y una correcta gestión presupuestaria.",
    allCaps: [{cap:"Storytelling",puntaje:2,nivel:"Competent"},{cap:"Gestión de riesgo",puntaje:2,nivel:"Competent"},{cap:"Análisis de Costos",puntaje:2.4,nivel:"Proficient"},{cap:"Desarrollo de casos de negocio",puntaje:2,nivel:"Competent"},{cap:"Planificación y análisis financiero",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión del conocimiento",puntaje:2.4,nivel:"Proficient"},{cap:"Excel",puntaje:2.5,nivel:"Proficient"},{cap:"Pronóstico",puntaje:2,nivel:"Competent"},{cap:"Gestión del cambio",puntaje:2.3,nivel:"Proficient"},{cap:"Informes Financieros",puntaje:2,nivel:"Competent"},{cap:"Inglés",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:2,nivel:"Competent"}]
  },
  "Site PPM": {
    descFull: "Sus actividades incluyen (entre otras) la estrecha colaboración con el equipo local, la comunicación del calendario del plan anual, los hitos y los indicadores clave de rendimiento (PI) para la cadena de suministro de ABI, la consolidación y comunicación de riesgos y oportunidades, y el liderazgo de iniciativas.",
    allCaps: [{cap:"Storytelling",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Gestión de riesgo",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Análisis de Costos",puntaje:2.3,nivel:"Proficient"},{cap:"Desarrollo de casos de negocio",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Planificación y análisis financiero",puntaje:1.8,nivel:"Competent"},{cap:"Gestión del conocimiento",puntaje:2.3,nivel:"Proficient"},{cap:"Excel",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión del cambio",puntaje:1.8,nivel:"Competent"},{cap:"Informes Financieros",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Inglés",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Colaboración",puntaje:1.8,nivel:"Competent"}]
  },
  "Gerente de Logística": {
    descFull: "El objetivo del Gerente de Logística es validar los planos tácticos de producción y elaboración de cerveza, así como operación de la recepción y asegurar el almacenamiento y suministro de los insumos requeridos para el proceso de envasado de cerveza, así como el correcto embarque del producto terminado cumpliendo con los estándares establecidos de ABInBev.",
    allCaps: [{cap:"Gestión de equipos",puntaje:2.3,nivel:"Proficient"},{cap:"Gestion de Interesados",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión de la cadena de suministro",puntaje:2.2,nivel:"Competent"},{cap:"Logística del Transporte",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de crisis",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"},{cap:"Finanzas",puntaje:1.9,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:1.8,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.8,nivel:"Competent"}]
  },
  "Gerente de Almacén BU": {
    descFull: "El objetivo del Gerente de Almacén es asegurar la eficiencia operativa y vigilar el cumplimiento de los indicadores y metas estratégicas; acompañando en el diseño, evolución y evaluación de las intervenciones requeridas para el alcance de las metas planteadas en cada planta.",
    allCaps: [{cap:"Gestión de equipos",puntaje:2.3,nivel:"Proficient"},{cap:"Gestion de Interesados",puntaje:2.2,nivel:"Competent"},{cap:"Grit (resilencia + empuje)",puntaje:2.2,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:2.1,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:1.8,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.8,nivel:"Competent"},{cap:"Organización avanzada",puntaje:1.7,nivel:"Competent"}]
  },
  "Gerente de Transporte (TM) T1": {
    descFull: "El Gerente Nacional de Transporte T1 es responsable de liderar las operaciones de transporte a nivel nacional, y es responsable de la planificación, coordinación y supervisión de las operaciones de transporte dentro de un país. Su objetivo es garantizar que los productos se entreguen de manera eficiente y puntual, minimizando costos y cumpliendo con las regulaciones. Debe manejar relaciones con proveedores, optimizar rutas y gestionar el equipo de transporte para mantener altos niveles de servicio y satisfacción del cliente.",
    allCaps: [{cap:"Gestion de Interesados",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de equipos",puntaje:2.4,nivel:"Proficient"},{cap:"Data Driven / Analítico",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión de la cadena de suministro",puntaje:2.3,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.2,nivel:"Competent"},{cap:"Logística de Planeación y Ejecución",puntaje:2.2,nivel:"Competent"},{cap:"Logística del Transporte",puntaje:2.1,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de crisis",puntaje:2.1,nivel:"Competent"},{cap:"Grit (resilencia + empuje)",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"}]
  },
  "Especialista de Transporte (TM) T1": {
    descFull: "El Especialista de Transporte  es responsable de planificar, coordinar y optimizar el transporte de bienes y materiales. Este rol implica asegurar la eficiencia en las rutas, la puntualidad en las entregas, la reducción de costos y el cumplimiento de las normativas vigentes. Los especialistas de transporte deben gestionar relaciones con proveedores y transportistas, así como resolver problemas logísticos que puedan surgir durante el proceso.",
    allCaps: [{cap:"Logística del Transporte",puntaje:1.9,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.9,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.8,nivel:"Competent"},{cap:"Colaboración",puntaje:1.8,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.8,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.7,nivel:"Competent"},{cap:"Finanzas",puntaje:1.7,nivel:"Competent"},{cap:"Optimización",puntaje:1.7,nivel:"Competent"},{cap:"Adaptabilidad",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
  "Gerente de Flota (TM) T1": {
    descFull: "El Gerente Nacional de Flota T1 es responsable de la gestión integral de una flota de vehículos a nivel nacional. Este rol incluye la supervisión del mantenimiento de la flota, la optimización de rutas, la gestión de presupuestos y la implementación de políticas de seguridad y cumplimiento normativo. El gerente debe asegurar que la flota opere de manera eficiente y rentable, minimizando los tiempos de inactividad y maximizando la disponibilidad de los vehículos",
    allCaps: [{cap:"Gestión de flota",puntaje:2.4,nivel:"Proficient"},{cap:"Gestion de Interesados",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión de equipos",puntaje:2.3,nivel:"Proficient"},{cap:"Seguridad",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"},{cap:"Gestión de contratos",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:1.9,nivel:"Competent"},{cap:"Management by Walking Around (MBWA)",puntaje:1.9,nivel:"Competent"},{cap:"Grit (resilencia + empuje)",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.8,nivel:"Competent"},{cap:"Trabajo bajo presión",puntaje:1.8,nivel:"Competent"}]
  },
  "Especialista de Transport Scheduling": {
    descFull: "Brindar soporte continuo y eficiente a las operaciones diarias y rutinarias de TMS, generando información para el análisis de indicadores clave de desempeño que permitan monitorear y desarrollar nuevos escenarios que brinden sostenibilidad a las operaciones del TMS y sus funcionalidades.",
    allCaps: [{cap:"Sistemas de gestión de transporte​",puntaje:2.1,nivel:"Competent"},{cap:"Comunicación",puntaje:2.1,nivel:"Competent"},{cap:"ITIL + COBIT",puntaje:2.1,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.9,nivel:"Competent"},{cap:"Colaboración",puntaje:1.9,nivel:"Competent"},{cap:"Trabajo bajo presión",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.7,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.7,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Finanzas",puntaje:1.4,nivel:"Advanced Beginner"}]
  },
  "Gerente de Transport Scheduling": {
    descFull: "El manager de Transport Management System lidera las actualizaciones y mejoras del Sistema de Gestión de Transporte, garantizando el soporte continuo y eficiente a las operaciones diarias y rutinariaS; coordinando el soporte a la programación de transporte (LCP) y gestionanando herramientas técnicas globales. ",
    allCaps: [{cap:"Gestion de Interesados",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2.2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2.2,nivel:"Competent"},{cap:"Sistemas de gestión de transporte​",puntaje:2.2,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.8,nivel:"Competent"},{cap:"Mejora continua",puntaje:1.8,nivel:"Competent"},{cap:"Finanzas",puntaje:1.7,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.7,nivel:"Competent"},{cap:"Compliance de transporte (país)",puntaje:1.7,nivel:"Competent"}]
  },
  "Gerente de Transport Execution": {
    descFull: "Garantizar la eficiente y segura operación de la flota de transporte, optimizando la ejecución de las entregas y recogidas de mercancías, minimizando costos y mejorando la satisfacción del cliente mediante una gestión efectiva de recursos (personas, equipos, flota).",
    allCaps: [{cap:"Gestión de equipos",puntaje:2.4,nivel:"Proficient"},{cap:"Gestion de Interesados",puntaje:2.3,nivel:"Proficient"},{cap:"Grit (resilencia + empuje)",puntaje:2.2,nivel:"Competent"},{cap:"Logística del Transporte",puntaje:2.2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.1,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2.1,nivel:"Competent"},{cap:"Finanzas",puntaje:1.8,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.8,nivel:"Competent"}]
  },
  "Coordinador de Transport Execution": {
    descFull: "Este rol tiene como objetivo supervisar y coordinar las operaciones diarias de transporte, asegurando que las mercancías se entreguen de manera eficiente, segura y puntual.",
    allCaps: [{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.9,nivel:"Competent"},{cap:"Gestión de crisis",puntaje:1.9,nivel:"Competent"},{cap:"Negociación",puntaje:1.9,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.9,nivel:"Competent"},{cap:"Logística del Transporte",puntaje:1.9,nivel:"Competent"},{cap:"Grit (resilencia + empuje)",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.7,nivel:"Competent"},{cap:"Finanzas",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Gestión de la cadena de suministro",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
  "Gerente de Control Tower T1": {
    descFull: "El Gerente de Control Tower se encarga de gestionar el seguimiento a las unidades de transporte de T1 para la prevención de accidentes y riesgos en las rutas de Transporte y el cumplimiento a la carga y entrega del producto terminado; maximizando la productividad de la flota. ",
    allCaps: [{cap:"Gestión de equipos",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión de crisis",puntaje:2.3,nivel:"Proficient"},{cap:"Gestión por sistemas",puntaje:2.2,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:2.1,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2,nivel:"Competent"},{cap:"Seguridad",puntaje:1.9,nivel:"Competent"},{cap:"Logística del Transporte",puntaje:1.9,nivel:"Competent"},{cap:"Resiliencia",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:1.9,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.8,nivel:"Competent"}]
  },
  "Coordinador de Control Tower T1 ": {
    descFull: "El coordinador de Control Tower de T1 tiene como objetivo supervisar y gestionar la ejecución de las operaciones diarias de las unidades de transporte, asegurando la eficiencia y la seguridad en el tránsito de mercancías... ",
    allCaps: [{cap:"Gestión por sistemas",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2.2,nivel:"Competent"},{cap:"Comunicación",puntaje:1.9,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.8,nivel:"Competent"},{cap:"Negociación",puntaje:1.8,nivel:"Competent"},{cap:"Trabajo bajo presión",puntaje:1.7,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:1.7,nivel:"Competent"},{cap:"Logística del Transporte",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Resolución de problemas",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Finanzas",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
  "Responsable de Almacén Operación": {
    descFull: "El objetivo del Responsable de Almacén es brindar seguimiento a la operación de acuerdo a los recursos que se tiene, asegurando se cumpla al 100% con la correcta operación de los procesos de  recepción, almacenamiento y suministro de los insumos requeridos para el proceso de envasado de cerveza y del correcto embarque del PT:  cumpliendo con los estándares establecidos en AB Inbev ",
    allCaps: [{cap:"Gestión de equipos",puntaje:2.1,nivel:"Competent"},{cap:"Management by Walking Around (MBWA)",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.9,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.7,nivel:"Competent"},{cap:"Finanzas",puntaje:1.7,nivel:"Competent"},{cap:"Almacenamiento Digital",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Toma de Decisiones",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Logística del Transporte",puntaje:1.4,nivel:"Advanced Beginner"}]
  },
  "Responsable de Control Operación": {
    descFull: "El objetivo del Responsable de Control Operación se encarga de inspeccionar los procesos de control de materiales en las operaciones, la implementación de rutinas de control con el objetivo de eliminar los impactos en la cadena de suministro, las pérdidas, diferencias en inventarios, control de insumos, etc.",
    allCaps: [{cap:"Gestión de inventarios",puntaje:2.2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2.2,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.9,nivel:"Competent"},{cap:"Management by Walking Around (MBWA)",puntaje:1.9,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:1.9,nivel:"Competent"},{cap:"Finanzas",puntaje:1.7,nivel:"Competent"},{cap:"Ética laboral",puntaje:1.7,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.7,nivel:"Competent"},{cap:"Negociación",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Gestión de la cadena de suministro",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
  "Responsable de Planeación Operación": {
    descFull: "El objetivo del Responsable de Planeación Operación directo en la operación de planta es ejecutar las actividades relacionadas a la planeación de producción detallada de producto terminado, reuniendo y validando información de cerveza, materiales, demanda del mercado y política de stock, para asegurar la mejor opción de producción dando cumplimiento a políticas, lotes y necesidades.",
    allCaps: [{cap:"Gestión de la cadena de suministro",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:2.1,nivel:"Competent"},{cap:"Técnicas de programación",puntaje:2,nivel:"Competent"},{cap:"Resiliencia",puntaje:2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2,nivel:"Competent"},{cap:"Colaboración",puntaje:1.9,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.7,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Finanzas",puntaje:1.4,nivel:"Advanced Beginner"},{cap:"Principios de Manufactura",puntaje:1.4,nivel:"Advanced Beginner"}]
  },
  "Especialista de Almacenaje de BU T1": {
    descFull: "El objetivo del Especialista de Almacén de BU es centralizar los resultados que arrojan las diferentes plantas en sus operaciones, para vigilar el cumplimiento de los indicadores y metas estratégicas; acompañando en el diseño, evolución y evaluación de las intervenciones requeridas para el alcance de las metas planteadas en cada planta.",
    allCaps: [{cap:"Gestión de inventarios",puntaje:2.1,nivel:"Competent"},{cap:"Pensamiento crítico",puntaje:2.1,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2,nivel:"Competent"},{cap:"Empuje",puntaje:1.9,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.9,nivel:"Competent"},{cap:"Mejora continua",puntaje:1.7,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.7,nivel:"Competent"},{cap:"Management by Walking Around (MBWA)",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Negociación",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Finanzas",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Colaboración",puntaje:1.5,nivel:"Advanced Beginner"}]
  },
  "Especialista de Control de BU T1": {
    descFull: "El objetivo del Especialista de Control  en BU es inspeccionar los procesos de control de materiales en las operaciones, la implementación de rutinas de control con el objetivo de eliminar los impactos en la cadena de suministro, las pérdidas, diferencias en inventarios, control de insumos, etc. Este rol busca estandarizar procedimientos, optimizar recursos y minimizar los riesgos operativos y financieros asociados a la gestión de inventarios y la producción a través de las distintas instalaciones que supervisa.",
    allCaps: [{cap:"Data Driven / Analítico",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2.1,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.9,nivel:"Competent"},{cap:"Mejora continua",puntaje:1.9,nivel:"Competent"},{cap:"Autonomía",puntaje:1.9,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.9,nivel:"Competent"},{cap:"Gestión de la cadena de suministro",puntaje:1.8,nivel:"Competent"},{cap:"Impacto e influencia",puntaje:1.8,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.7,nivel:"Competent"},{cap:"Ética laboral",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Finanzas",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
  "Gerente de Control y Productividad": {
    descFull: "El Gerente de Control y Productividad en el área de Almacenaje tiene el objetivo de asegurar la eficiencia operativa y la maximización de recursos dentro de la planta, alineando los procesos de control y productividad con los objetivos estratégicos del Gerente de Logística. Este rol se enfoca en optimizar las operaciones del almacén y de logística, mejorando continuamente la calidad, el rendimiento y la eficiencia para cumplir con los requerimientos de la cadena de suministro.",
    allCaps: [{cap:"Data Driven / Analítico",puntaje:2.2,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de inventarios",puntaje:2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:1.9,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.9,nivel:"Competent"},{cap:"Productividad",puntaje:1.8,nivel:"Competent"},{cap:"Finanzas",puntaje:1.7,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:1.7,nivel:"Competent"},{cap:"Ética laboral",puntaje:1.7,nivel:"Competent"},{cap:"Organización avanzada",puntaje:1.7,nivel:"Competent"}]
  },
  "Gerente Senior COMEX": {
    descFull: "Asegurar el cumplimiento de los requerimientos de la BU y stakeholders, en el mejor tiempo posible, siempre cuidando los costos y evitando hacer extracostos.",
    allCaps: [{cap:"Gestion de Interesados",puntaje:2.3,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.3,nivel:"Proficient"},{cap:"Planificación de la estrategia",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de contratos",puntaje:2.2,nivel:"Competent"},{cap:"Grit (resilencia + empuje)",puntaje:2.2,nivel:"Competent"},{cap:"Conocimiento de Comercio Exterior",puntaje:2.2,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:2.1,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2.1,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2.1,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2,nivel:"Competent"}]
  },
  "Coordinador de COMEX": {
    descFull: "Monitrear el flujo de información y datos de manera diaria, semanal y mensual que se generan en la torre de comercio exterior, informando sobre el comportamiento de los KPI`s del área a la Gerencia de Imports y Exports.",
    allCaps: [{cap:"Autonomía",puntaje:2.1,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:2.1,nivel:"Competent"},{cap:"Pensamiento crítico",puntaje:2.1,nivel:"Competent"},{cap:"Finanzas",puntaje:1.9,nivel:"Competent"},{cap:"Comunicación",puntaje:1.9,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.9,nivel:"Competent"},{cap:"Colaboración",puntaje:1.9,nivel:"Competent"},{cap:"Conocimiento de Comercio Exterior",puntaje:1.9,nivel:"Competent"},{cap:"Proactividad",puntaje:1.8,nivel:"Competent"},{cap:"Impacto e influencia",puntaje:1.8,nivel:"Competent"}]
  },
  "Gerente Junior COMEX": {
    descFull: "Supervisar las actividades de trabajo de los especialistas de importación y exportación; a fin de garantizar la coordinación de emabaques, la importación y exportación de materias primas; realizando las gestiones necesarias con los proveedores y vigilando el cumplimiento de los costos asignados.",
    allCaps: [{cap:"Finanzas",puntaje:2.1,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.1,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:2,nivel:"Competent"},{cap:"Conocimiento de Comercio Exterior",puntaje:2,nivel:"Competent"},{cap:"Gestión de equipos",puntaje:2,nivel:"Competent"},{cap:"Solución de problemas y causa raíz",puntaje:1.9,nivel:"Competent"},{cap:"Empuje",puntaje:1.9,nivel:"Competent"},{cap:"Pensamiento crítico",puntaje:1.9,nivel:"Competent"},{cap:"Impacto e influencia",puntaje:1.9,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:1.9,nivel:"Competent"}]
  },
  "Especialista Import-Export": {
    descFull: "Coordianar las actividades para la importación de materia prima en tiempo, evitando la genracion de extra costos y cumpliendo con las necesidades de nuestros clientes.  ",
    allCaps: [{cap:"Finanzas",puntaje:1.9,nivel:"Competent"},{cap:"Conocimiento de Comercio Exterior",puntaje:1.9,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:1.8,nivel:"Competent"},{cap:"Empuje",puntaje:1.8,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:1.8,nivel:"Competent"},{cap:"Gestión de riesgos",puntaje:1.8,nivel:"Competent"},{cap:"Resolución de problemas",puntaje:1.8,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:1.7,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Trabajo bajo presión",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
  "Analista Import-Export": {
    descFull: "Coordianar las actividades para la exportación de producto terminado en tiempo, evitando la genracion de extra costos y cumpliendo con las necesidades de nuestros clientes.  ",
    allCaps: [{cap:"Finanzas",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Conocimiento de Comercio Exterior",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Planificación y Organización",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Proactividad",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Gestión por sistemas",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Resolución de problemas",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Gestión de riesgos",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Colaboración",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Data Driven / Analítico",puntaje:1.5,nivel:"Advanced Beginner"},{cap:"Trabajo bajo presión",puntaje:1.5,nivel:"Advanced Beginner"}]
  },
  "Gerente de Planning BU": {
    descFull: "Este rol es responsable de liderar, supervisar y optimizar los procesos de planificación en todas las áreas de una o más BUs, asegurando la alineación táctica y operativa con los objetivos estratégicos del negocio. Esto incluye garantizar el cumplimiento del plan de demanda, materiales, envase, producción y distribución establecidos. Promover acciones proactivas para ofrecer planes más confiables y asegurar una operación ágil, integrada y en constante mejora continua para lograr el cumplimiento de las metas del negocio.",
    allCaps: [{cap:"Gestión de la cadena de suministro",puntaje:2.7,nivel:"Expert"},{cap:"Gestión de equipos",puntaje:2.6,nivel:"Proficient"},{cap:"Gestión de interesados",puntaje:2.5,nivel:"Proficient"},{cap:"Data Driven / Analítico",puntaje:2.5,nivel:"Proficient"},{cap:"Toma de Decisiones",puntaje:2.4,nivel:"Proficient"},{cap:"Planeación Operativa de Supply Chain",puntaje:2.3,nivel:"Proficient"},{cap:"Planificación de la estrategia",puntaje:2.3,nivel:"Proficient"},{cap:"Grit (resilencia + empuje)",puntaje:2.3,nivel:"Proficient"},{cap:"Finanzas",puntaje:2.2,nivel:"Competent"},{cap:"Pensamiento Sistémico",puntaje:2.2,nivel:"Competent"},{cap:"Mentalidad de crecimiento",puntaje:2.2,nivel:"Competent"},{cap:"Inglés",puntaje:2.3,nivel:"Proficient"}]
  },
  "Especialista DPO": {
    descFull: "Garantizar la correcta implementación y ejecución del programa de gestión DPO.",
    allCaps: [{cap:"Empuje / Orientación a resultados",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión por sistemas",puntaje:2.4,nivel:"Proficient"},{cap:"Comunicación",puntaje:2.3,nivel:"Proficient"},{cap:"Data Driven / Analítico",puntaje:2.2,nivel:"Competent"},{cap:"Autonomía",puntaje:2.1,nivel:"Competent"},{cap:"Inteligencia emocional",puntaje:2.1,nivel:"Competent"},{cap:"Mejora continua",puntaje:2,nivel:"Competent"},{cap:"Toma de Decisiones",puntaje:2,nivel:"Competent"},{cap:"Impacto e influencia",puntaje:1.9,nivel:"Competent"},{cap:"Planificación y Organización",puntaje:1.8,nivel:"Competent"}]
  },
  "Manager DPO- Safety": {
    descFull: "El Gerente DPO-Safety es el responsable de la implementación de estándares de gestión de DPO para T2, garantizando que su personal aplique los procedimientos, recomendaciones y pilares de gestión en los diferentes centros de distribución. Además, es responsable de safety, supervisando el programa de seguridad para diferentes almacenes y centros de distribución. Se enfoca en la planeación estratégica de cursos de seguridad, con un enfoque de 0 accidentes o errores. Su enfoque es el control de riesgos de la operación, análisis de datos para prevenir riesgos y supervisar el depliegue de programas de seguridad.",
    allCaps: [{cap:"Seguridad",puntaje:2.6,nivel:"Proficient"},{cap:"Data Driven / Analítico",puntaje:2.5,nivel:"Proficient"},{cap:"Gestión de riesgos",puntaje:2.4,nivel:"Proficient"},{cap:"Gestión de equipos",puntaje:2.4,nivel:"Proficient"},{cap:"Empuje",puntaje:2.3,nivel:"Proficient"},{cap:"Toma de Decisiones",puntaje:2.2,nivel:"Competent"},{cap:"Gestion de Interesados",puntaje:2.2,nivel:"Competent"},{cap:"Gestión por sistemas",puntaje:2.2,nivel:"Competent"},{cap:"Inglés",puntaje:2.2,nivel:"Competent"},{cap:"Autonomía",puntaje:2,nivel:"Competent"}]
  },
  "Especialista de Simulación": {
    descFull: "El Gerente DPO-Safety es el responsable de la implementación de estándares de gestión de DPO para T2, garantizando que su personal aplique los procedimientos, recomendaciones y pilares de gestión en los diferentes centros de distribución. Además, es responsable de safety, supervisando el programa de seguridad para diferentes almacenes y centros de distribución. Se enfoca en la planeación estratégica de cursos de seguridad, con un enfoque de 0 accidentes o errores. Su enfoque es el control de riesgos de la operación, análisis de datos para prevenir riesgos y supervisar el depliegue de programas de seguridad.",
    allCaps: [{cap:"Empuje / Orientación a resultados",puntaje:2,nivel:"Competent"},{cap:"Programación Estructurada",puntaje:2,nivel:"Competent"},{cap:"Data Driven / Analítico",puntaje:1.8,nivel:"Competent"},{cap:"Comunicación",puntaje:1.8,nivel:"Competent"},{cap:"Metodología de Simulación",puntaje:1.8,nivel:"Competent"},{cap:"Inglés",puntaje:1.7,nivel:"Competent"},{cap:"Optimización",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Autonomía",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Uso de FlexSim",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Probabilidad y Estadística",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Autodidacta",puntaje:1.6,nivel:"Advanced Beginner"},{cap:"Pensamiento Lateral",puntaje:1.6,nivel:"Advanced Beginner"}]
  },
};

